
INSERT INTO tb_game_list (nome) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (nome) VALUES ('Jogos de plataforma');


INSERT into tb_game(titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao ) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'teste', 'os humanos descobrem nas ruínas de Marte uma tecnologia da mítica raça alienígena Prothean que os permitem viajar longas distâncias. A descoberta causou um enorme avanço tecnológico e inaugurou uma era de exploração espacial da humanidade, colocando-a no mapa político das espécies que controlam a Via Láctea.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'teste', 'Ambientado em 1899, o jogo segue Arthur Morgan, um criminoso membro da gangue Van der Linde, uma das mais famosas dos Estados Unidos durante o declínio do Velho Oeste Americano');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao ) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'teste','Conta a aventura do bruxo Geralt de Rívia em busca da sua filha, Ciri, enquanto enfrenta inimigos mortais e explora um mundo cheio de possibilidades, desafios e aventuras');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'teste','Torne-se um shinobi extremamente talentoso, o "lobo de um braço". Após ser derrotado por um samurai sombrio Ashina, desperte para o seu destino, recupere o seu mestre e se vingue do seu inimigo a todo custo.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao ) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'teste','Ambientado na ilha de Tsushima durante o século XIII, época onde o império mongol assolava a ásia, conquistando territórios e destruindo qualquer inimigo pela frente. A ilha é invadida por Khotun Khan, um general fictício fortemente inspirado pelo poderoso Kublai Khan.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'teste','Mario aparece pela primeira vez como “Jumpman” no jogo “Donkey Kong”, no qual ele precisa salvar sua namorada “Pauline” do gorila. Originalmente, ele era carpinteiro. No entanto, ao entrar nos canos em seu próprio jogo, “Mario Bros”, passou a ser considerado um encanador');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'teste','O mundo de Hollow Knight é habitado por insetos antropomórficos que viviam em uma cidade subterrânea, até que um tipo de contaminação enlouqueceu as criaturas. O Hollow Knight, personagem principal que carrega o nome do jogo ("cavaleiro vazio" em inglês), é um tipo de receptáculo criado para combater essa infecção.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao ) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'teste','Ori é o primeiro Orixá a ser louvado, representação particular da existência individualizada (a essência real do ser). É aquele que guia, acompanha e ajuda a pessoa desde antes do nascimento, durante toda vida e após a morte, referenciando sua caminhada e a assistindo no cumprimento de seu destino.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'teste',' Opersonagem-título e seu irmão Mugman caíram na lorota do Diabo em pessoa, fizeram uma aposta tentando ficar ricos e obviamente se estreparam, pois acabaram negociado suas almas.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, pequena_descricao, longa_descricao ) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'teste','Se passa no Little Planet, um pequeno mundo que surge em Never Lakes durante um mês do ano. Nele, o passado, o presente e o futuro se unem formando as Time Stones, pedras que dão o poder de viajar no tempo. Eggman descobre a existência delas e decide encontrá-las antes de Sonic.');

INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 10, 4)
